name=esp_cron
version=0.0.5
author=Asim Zulfiqar
maintainer=Asim Zulfiqar <emmiasim67@gmail.com>
sentence=CRON-style scheduler for ESP32 (Arduino Port)
paragraph=Arduino-compatible port of the esp_cron ESP-IDF component.
category=Timing
url=https://github.com/asimzulfiqar/esp_cron
architectures=esp32
